fix wrong link
jenkinsci/built-on-column-plugin pull request #2
Opened 2020-05-12 09:18 UTC by zhaoying818

2020-05-12 12:18 UTC, voorth commented
Hmm... the "absolute" path has worked flawlessly for the last 9 years - are you sure this is needed?

2020-05-12 14:05 UTC, zhaoying818 commented
> 
> 
> Hmm... the "absolute" path has worked flawlessly for the last 9 years - are you sure this is needed?

when jenkins url is like xxx.com/aaa/bbb , the latest plugin is link to xxx.com/computer/yyy , and is 404

2020-11-05 07:19 UTC, Absh-Day commented
@zhaoying818 I was about to raise the same issue then found this PR.
The maven build fails with Caused by: java.lang.ClassNotFoundException: com.sun.mirror.apt.AnnotationProcessorFactory
It seems issue with java8, should work with older versions.

2020-12-07 18:13 UTC, qBTp requested changes

2020-12-07 18:13 UTC, qBTp commented on pom.xml
> -  <version>1.2-SNAPSHOT</version>
Keep SNAPSHOT in.

2021-01-05 17:45 UTC, zhaoying818 commented
> 
> 
> @zhaoying818 I was about to raise the same issue then found this PR.
> The maven build fails with Caused by: java.lang.ClassNotFoundException: com.sun.mirror.apt.AnnotationProcessorFactory
> It seems issue with java8, should work with older versions.

I did some change. You can try it.

2021-01-16 16:27 UTC, zhaoying818 commented
@olivergondza

2022-11-23 18:28 UTC, MarkEWaite commented
Thanks for the contribution.  Most crucial changes have been merged in #4 , #6 .  Unwilling to change the package of the plugin because that seems unnecessary.

2022-11-23 18:28 UTC, closed without merging