[JENKINS-46773] Fix link from built on column to agent page
jenkinsci/built-on-column-plugin pull request #20
Opened 2023-04-11 17:11 UTC by janasrikanth

## [JENKINS-46773](https://issues.jenkins.io/browse/JENKINS-46773) Fix link from built on column to agent page

The real node is `https://<hostname>/<project>/computer/<node>` but this plugin reports the node is `https://<hostname>/computer/<node>`

2023-04-11 17:48 UTC, MarkEWaite requested changes
Thanks very much @janasrikanth .  That resolved the issue for jobs at the root of the Jenkins hierarchy.  Unfortunately, it does not resolve it for the jobs that are created in a folder.  Steps that I took to see the failure when a job is in a folder:

1. Run the plugin with `mvn clean -Dhost=0.0.0.0 -Djenkins.version=2.387.2 hpi:run`
2. Install the ssh-build-agent plugin and the folders plugin from the plugin manager page of Manage Jenkins
3. Configure two agents, `node-a` and `node-b`
4. Run processes in other windows that provide those agents
5. Disable execution on the controller by setting the number of executors on the controller to 0
6. Define a folder by clicking "New item" and continuing through the pages
7. Define a job inside the folder
8. Run the job
9. See the "built-on" column shows the expected agent
10. Click the "built-on" column to confirm that it reports an error

```
404 Not Found
Stapler processed this HTTP request as follows, but couldn't find the resource to consume the request

-> evaluate(<hudson.model.Hudson@2bd60bc0> :hudson.model.Hudson,"/job/A-Folder/manage/computer/a-node")
-> evaluate(((StaplerProxy)<hudson.model.Hudson@2bd60bc0>).getTarget(),"/job/A-Folder/manage/computer/a-node")
-> evaluate(<hudson.model.Hudson@2bd60bc0>.getJob("A-Folder"),"/manage/computer/a-node")
-> evaluate(<com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder]> :com.cloudbees.hudson.plugins.folder.Folder,"/manage/computer/a-node")
-> evaluate(((StaplerProxy)<com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder]>).getTarget(),"/manage/computer/a-node")
-> evaluate(<com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder]>.getDynamic("manage",...),"/computer/a-node")
            com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder].getDynamic("manage",...)==null. Back tracking.
-> evaluate(((StaplerFallback)<com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder]>).getStaplerFallback(),"/manage/computer/a-node")
-> evaluate(<hudson.model.AllView@4096d274[job/A-Folder/view/All/]> :hudson.model.AllView,"/manage/computer/a-node")
-> evaluate(<hudson.model.AllView@4096d274[job/A-Folder/view/All/]>.getDynamic("manage",...),"/computer/a-node")
            hudson.model.AllView@4096d274[job/A-Folder/view/All/].getDynamic("manage",...)==null. Back tracking.
-> No matching rule was found on <hudson.model.AllView@4096d274[job/A-Folder/view/All/]> for "/manage/computer/a-node"
```
```

2023-04-11 18:19 UTC, janasrikanth commented
Thanks for reviewing. I will check this issue

2023-04-11 19:49 UTC, janasrikanth commented
> Thanks very much @janasrikanth . That resolved the issue for jobs at the root of the Jenkins hierarchy. Unfortunately, it does not resolve it for the jobs that are created in a folder. Steps that I took to see the failure when a job is in a folder:
> 
> 1. Run the plugin with `mvn clean -Dhost=0.0.0.0 -Djenkins.version=2.387.2 hpi:run`
> 2. Install the ssh-build-agent plugin and the folders plugin from the plugin manager page of Manage Jenkins
> 3. Configure two agents, `node-a` and `node-b`
> 4. Run processes in other windows that provide those agents
> 5. Disable execution on the controller by setting the number of executors on the controller to 0
> 6. Define a folder by clicking "New item" and continuing through the pages
> 7. Define a job inside the folder
> 8. Run the job
> 9. See the "built-on" column shows the expected agent
> 10. Click the "built-on" column to confirm that it reports an error
> 
> ```
> 404 Not Found
> Stapler processed this HTTP request as follows, but couldn't find the resource to consume the request
> 
> -> evaluate(<hudson.model.Hudson@2bd60bc0> :hudson.model.Hudson,"/job/A-Folder/manage/computer/a-node")
> -> evaluate(((StaplerProxy)<hudson.model.Hudson@2bd60bc0>).getTarget(),"/job/A-Folder/manage/computer/a-node")
> -> evaluate(<hudson.model.Hudson@2bd60bc0>.getJob("A-Folder"),"/manage/computer/a-node")
> -> evaluate(<com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder]> :com.cloudbees.hudson.plugins.folder.Folder,"/manage/computer/a-node")
> -> evaluate(((StaplerProxy)<com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder]>).getTarget(),"/manage/computer/a-node")
> -> evaluate(<com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder]>.getDynamic("manage",...),"/computer/a-node")
>             com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder].getDynamic("manage",...)==null. Back tracking.
> -> evaluate(((StaplerFallback)<com.cloudbees.hudson.plugins.folder.Folder@169f7cd9[A-Folder]>).getStaplerFallback(),"/manage/computer/a-node")
> -> evaluate(<hudson.model.AllView@4096d274[job/A-Folder/view/All/]> :hudson.model.AllView,"/manage/computer/a-node")
> -> evaluate(<hudson.model.AllView@4096d274[job/A-Folder/view/All/]>.getDynamic("manage",...),"/computer/a-node")
>             hudson.model.AllView@4096d274[job/A-Folder/view/All/].getDynamic("manage",...)==null. Back tracking.
> -> No matching rule was found on <hudson.model.AllView@4096d274[job/A-Folder/view/All/]> for "/manage/computer/a-node"
> ```

Hi @MarkEWaite 
Applied a Fix, Please check

2023-04-11 23:53 UTC, MarkEWaite approved these changes
Matches with the uses of `${rootURL}` in Jenkins core.  Thanks!

2023-04-11 23:53 UTC, merged

2023-04-12 00:03 UTC, MarkEWaite commented
Released in 1.4.  Thanks @janasrikanth